container:
  image: python:3.7

pep8_task:
  timeout_in: 5m
  script:
    - pip install -r flake.requirements.txt -U
    - flake8 --config ./flake8.ini

do_release_task:
  timeout_in: 5m
  only_if: $CIRRUS_TAG != ''
  environment:
    PYPI_USER: ENCRYPTED[!f420f18c71abb7de0526d87be49dacd930b1efeede565fb92ba8af50d63135aa63e061ff27e615bfa19056f6eda09b60!]
    PYPI_PASSWORD: ENCRYPTED[!935a3c5784e9057f0434c2ec6626b357ef47620158f48133be72d23dc6a26dc319b74b2b2face4ea503bbdbd7a723323!]
  depends_on:
    - pep8
  script:
    - pip install twine
    - ./genpypirc
    - python setup.py sdist
    - twine upload dist/*
