name: Check Python style

on: [push]

jobs:
  check_style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          python -m pip install -r flake.requirements.txt -U
      - name: check flake8
        run: |
          python -m flake8 --config ./flake8.ini

